server:
  port: 8080
spring:
  application:
    name: personal
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
     db1:
       url: jdbc:mysql://localhost:3306/personal_zc_01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
       username: root
       password: jiazhangjia217
       driver-class-name: com.mysql.jdbc.Driver
       initialSize: 5
       minIdle: 5
       maxActive: 20
     # 数据库 2
     db2:
       url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
       username: root
       password: jiazhangjia217
       driver-class-name: com.mysql.jdbc.Driver
       initialSize: 5
       minIdle: 5
       maxActive: 20
     # 数据库 3
     db3:
       url: jdbc:mysql://localhost:3306/personal_zc_wx_group?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
       username: root
       password: jiazhangjia217
       driver-class-name: com.mysql.jdbc.Driver
       initialSize: 5
       minIdle: 5
       maxActive: 20
     # 数据库 4
     db4:
       url: jdbc:mysql://localhost:3306/qunliebian_01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
       username: root
       password: jiazhangjia217
       driver-class-name: com.mysql.jdbc.Driver
       initialSize: 5
       minIdle: 5
       maxActive: 20
     connection-init-sqls: set names utf8mb4
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#全局日志级别
logging:
  level:
    root: error
mybatis-plus:
#  #mybatis日志打印
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #全局设置主键生成策略
  global-config:
    db-config:
      id-type: id_worker_str
#线下
fileServer:
  #文件上传服务器地址
  url: http://47.112.102.117:8080
  confUrl: F:/myproject/Idea/gerenhao/personalZCRobot/src/main/resources/tracker.conf
  ms_SERVER_ROOT_URL: http://www.jiazhang111.xyz
  qrurl: http://www.jiazhang111.xyz:9091

